title: Newtron Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://is.newtron.online'
params:
  alwaysKeepBrandColor: true
  autoRefresh: true
  brand: f2f2f2
  dateFormat: 'Monday, 02.01.2006 15:04'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: cc4400
  down: e60000
  googleAnalytics: UA-00000000-1
  incidentPostsPerPage: 10
  logo: /img/newtron_logo_rgb.png
  notice: 24478f
  ok: 008000
  shortDateFormat: '15:04 — 02.01.2006'
  systems:
    - description: nMarkets PROD Environment
      name: PROD
    - description: The guts of the application.
      name: API
    - description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      name: Media Proxy
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
